name: NewtonFarmStables
favicon: null
layout_spectrum: 0.4040262794587761
typography_spectrum: 0.7108996447641402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.48892929404973984
  lightness: 0.4613901579286903
  saturation: 0.8159953108988702
  rhythmicContrast: 0.5034937032032758
purpose: []
