name: NewtonFarmStables
favicon: null
layout_spectrum: 0.4040262794587761
typography_spectrum: 0.83494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcffff'
    - '#1d211e'
    - '#a2b4ca'
    - '#8d817d'
    - '#e9d4b2'
  brandStrength: 0.5
  lightness: 0.4613901579286903
  saturation: 0.8159953108988702
  rhythmicContrast: 0.5034937032032758
purpose: []
