name: Newton Farm Stables
favicon: null
layout_spectrum: 0.91042
typography_spectrum: 0.61116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcffff'
    - '#1d211e'
    - '#a2b4ca'
    - '#8d817d'
    - '#e9d4b2'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
